# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lausanne 2020
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lausanne2020.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass

languages: ["en","fr","de"]
exclude_from_localizations: ["js","css","_sass"]

contentful:
  spaces:
    - news: # Jekyll _data folder identifier - Required
        space: ENV_CONTENTFUL_SPACE_ID # Required
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN # Required
        cda_query:
          content_type: news
          order: -fields.date
          limit: 3
    - venues: # Jekyll _data folder identifier - Required
        space: ENV_CONTENTFUL_SPACE_ID # Required
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN # Required
        cda_query:
          content_type: venues
    - sectionSites: # Jekyll _data folder identifier - Required
        space: ENV_CONTENTFUL_SPACE_ID # Required
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN # Required
        cda_query:
          content_type: sectionSites
          order: -sys.createdAt
    - partnersLogos: # Jekyll _data folder identifier - Required
        space: ENV_CONTENTFUL_SPACE_ID # Required
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN # Required
        cda_query:
          content_type: partnersLogos
    - keyNumbers: # Jekyll _data folder identifier - Required
        space: ENV_CONTENTFUL_SPACE_ID # Required
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN # Required
        cda_query:
          content_type: keyNumbers

page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.news.news'
    template: 'single'
    name: 'titre'
    dir: 'news-fr'
  - data: 'contentful.spaces.news.news'
    template: 'single'
    name: 'titreDe'
    dir: 'news-de'